sudo: required
language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - sudo pip install awscli
before_script:
  - npm install
  - npm test
  - gulp
# Deploy using awscli to enable pruning of removed files
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: www.cafe-grundeinkommen.org
  skip_cleanup: true
  local_dir: build
  acl: public_read  
  on:
    branch: master
  region: $AWS_REGION
  cache_control: "max-age=21600"
after_deploy:
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
